/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliadosRouteImport } from './routes/aliados'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConvocatoriasRouteImport } from './routes/convocatorias'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as DirectorioRouteImport } from './routes/directorio'
import { Route as EcosistemaRouteImport } from './routes/ecosistema'
import { Route as EmpleoRouteImport } from './routes/empleo'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as HazParteRouteImport } from './routes/haz-parte'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as InnovacionRouteImport } from './routes/innovacion'
import { Route as InstitucionesRouteImport } from './routes/instituciones'
import { Route as InversionRouteImport } from './routes/inversion'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as TalentoRouteImport } from './routes/talento'
import { Route as UniversidadesRouteImport } from './routes/universidades'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as EcosistemaIndexRouteImport } from './routes/ecosistema.index'
import { Route as EcosistemaSlugRouteImport } from './routes/ecosistema.$slug'
import { Route as PodcastIndexRouteImport } from './routes/podcast.index'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliadosRoute = AliadosRouteImport.update({
  id: '/aliados',
  path: '/aliados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvocatoriasRoute = ConvocatoriasRouteImport.update({
  id: '/convocatorias',
  path: '/convocatorias',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioRoute = DirectorioRouteImport.update({
  id: '/directorio',
  path: '/directorio',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemaRoute = EcosistemaRouteImport.update({
  id: '/ecosistema',
  path: '/ecosistema',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleoRoute = EmpleoRouteImport.update({
  id: '/empleo',
  path: '/empleo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const HazParteRoute = HazParteRouteImport.update({
  id: '/haz-parte',
  path: '/haz-parte',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovacionRoute = InnovacionRouteImport.update({
  id: '/innovacion',
  path: '/innovacion',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionesRoute = InstitucionesRouteImport.update({
  id: '/instituciones',
  path: '/instituciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InversionRoute = InversionRouteImport.update({
  id: '/inversion',
  path: '/inversion',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentoRoute = TalentoRouteImport.update({
  id: '/talento',
  path: '/talento',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversidadesRoute = UniversidadesRouteImport.update({
  id: '/universidades',
  path: '/universidades',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemaIndexRoute = EcosistemaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcosistemaRoute,
} as any)
const EcosistemaSlugRoute = EcosistemaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EcosistemaRoute,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastRoute,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/datos': typeof DatosRoute
  '/directorio': typeof DirectorioRoute
  '/ecosistema': typeof EcosistemaRouteWithChildren
  '/empleo': typeof EmpleoRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/haz-parte': typeof HazParteRoute
  '/historias': typeof HistoriasRoute
  '/innovacion': typeof InnovacionRoute
  '/instituciones': typeof InstitucionesRoute
  '/inversion': typeof InversionRoute
  '/mapa': typeof MapaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/programas': typeof ProgramasRoute
  '/retos': typeof RetosRoute
  '/startups': typeof StartupsRoute
  '/talento': typeof TalentoRoute
  '/universidades': typeof UniversidadesRoute
  '/videos': typeof VideosRoute
  '/ecosistema/$slug': typeof EcosistemaSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/ecosistema/': typeof EcosistemaIndexRoute
  '/podcast/': typeof PodcastIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/datos': typeof DatosRoute
  '/directorio': typeof DirectorioRoute
  '/empleo': typeof EmpleoRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/haz-parte': typeof HazParteRoute
  '/historias': typeof HistoriasRoute
  '/innovacion': typeof InnovacionRoute
  '/instituciones': typeof InstitucionesRoute
  '/inversion': typeof InversionRoute
  '/mapa': typeof MapaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/programas': typeof ProgramasRoute
  '/retos': typeof RetosRoute
  '/startups': typeof StartupsRoute
  '/talento': typeof TalentoRoute
  '/universidades': typeof UniversidadesRoute
  '/videos': typeof VideosRoute
  '/ecosistema/$slug': typeof EcosistemaSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/ecosistema': typeof EcosistemaIndexRoute
  '/podcast': typeof PodcastIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/datos': typeof DatosRoute
  '/directorio': typeof DirectorioRoute
  '/ecosistema': typeof EcosistemaRouteWithChildren
  '/empleo': typeof EmpleoRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/haz-parte': typeof HazParteRoute
  '/historias': typeof HistoriasRoute
  '/innovacion': typeof InnovacionRoute
  '/instituciones': typeof InstitucionesRoute
  '/inversion': typeof InversionRoute
  '/mapa': typeof MapaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/programas': typeof ProgramasRoute
  '/retos': typeof RetosRoute
  '/startups': typeof StartupsRoute
  '/talento': typeof TalentoRoute
  '/universidades': typeof UniversidadesRoute
  '/videos': typeof VideosRoute
  '/ecosistema/$slug': typeof EcosistemaSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/ecosistema/': typeof EcosistemaIndexRoute
  '/podcast/': typeof PodcastIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliados'
    | '/contacto'
    | '/convocatorias'
    | '/datos'
    | '/directorio'
    | '/ecosistema'
    | '/empleo'
    | '/empresas'
    | '/eventos'
    | '/haz-parte'
    | '/historias'
    | '/innovacion'
    | '/instituciones'
    | '/inversion'
    | '/mapa'
    | '/nosotros'
    | '/noticias'
    | '/oportunidades'
    | '/podcast'
    | '/programas'
    | '/retos'
    | '/startups'
    | '/talento'
    | '/universidades'
    | '/videos'
    | '/ecosistema/$slug'
    | '/podcast/$slug'
    | '/ecosistema/'
    | '/podcast/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliados'
    | '/contacto'
    | '/convocatorias'
    | '/datos'
    | '/directorio'
    | '/empleo'
    | '/empresas'
    | '/eventos'
    | '/haz-parte'
    | '/historias'
    | '/innovacion'
    | '/instituciones'
    | '/inversion'
    | '/mapa'
    | '/nosotros'
    | '/noticias'
    | '/oportunidades'
    | '/programas'
    | '/retos'
    | '/startups'
    | '/talento'
    | '/universidades'
    | '/videos'
    | '/ecosistema/$slug'
    | '/podcast/$slug'
    | '/ecosistema'
    | '/podcast'
  id:
    | '__root__'
    | '/'
    | '/aliados'
    | '/contacto'
    | '/convocatorias'
    | '/datos'
    | '/directorio'
    | '/ecosistema'
    | '/empleo'
    | '/empresas'
    | '/eventos'
    | '/haz-parte'
    | '/historias'
    | '/innovacion'
    | '/instituciones'
    | '/inversion'
    | '/mapa'
    | '/nosotros'
    | '/noticias'
    | '/oportunidades'
    | '/podcast'
    | '/programas'
    | '/retos'
    | '/startups'
    | '/talento'
    | '/universidades'
    | '/videos'
    | '/ecosistema/$slug'
    | '/podcast/$slug'
    | '/ecosistema/'
    | '/podcast/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliadosRoute: typeof AliadosRoute
  ContactoRoute: typeof ContactoRoute
  ConvocatoriasRoute: typeof ConvocatoriasRoute
  DatosRoute: typeof DatosRoute
  DirectorioRoute: typeof DirectorioRoute
  EcosistemaRoute: typeof EcosistemaRouteWithChildren
  EmpleoRoute: typeof EmpleoRoute
  EmpresasRoute: typeof EmpresasRoute
  EventosRoute: typeof EventosRoute
  HazParteRoute: typeof HazParteRoute
  HistoriasRoute: typeof HistoriasRoute
  InnovacionRoute: typeof InnovacionRoute
  InstitucionesRoute: typeof InstitucionesRoute
  InversionRoute: typeof InversionRoute
  MapaRoute: typeof MapaRoute
  NosotrosRoute: typeof NosotrosRoute
  NoticiasRoute: typeof NoticiasRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  ProgramasRoute: typeof ProgramasRoute
  RetosRoute: typeof RetosRoute
  StartupsRoute: typeof StartupsRoute
  TalentoRoute: typeof TalentoRoute
  UniversidadesRoute: typeof UniversidadesRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliados': {
      id: '/aliados'
      path: '/aliados'
      fullPath: '/aliados'
      preLoaderRoute: typeof AliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convocatorias': {
      id: '/convocatorias'
      path: '/convocatorias'
      fullPath: '/convocatorias'
      preLoaderRoute: typeof ConvocatoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio': {
      id: '/directorio'
      path: '/directorio'
      fullPath: '/directorio'
      preLoaderRoute: typeof DirectorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistema': {
      id: '/ecosistema'
      path: '/ecosistema'
      fullPath: '/ecosistema'
      preLoaderRoute: typeof EcosistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleo': {
      id: '/empleo'
      path: '/empleo'
      fullPath: '/empleo'
      preLoaderRoute: typeof EmpleoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haz-parte': {
      id: '/haz-parte'
      path: '/haz-parte'
      fullPath: '/haz-parte'
      preLoaderRoute: typeof HazParteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovacion': {
      id: '/innovacion'
      path: '/innovacion'
      fullPath: '/innovacion'
      preLoaderRoute: typeof InnovacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituciones': {
      id: '/instituciones'
      path: '/instituciones'
      fullPath: '/instituciones'
      preLoaderRoute: typeof InstitucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversion': {
      id: '/inversion'
      path: '/inversion'
      fullPath: '/inversion'
      preLoaderRoute: typeof InversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talento': {
      id: '/talento'
      path: '/talento'
      fullPath: '/talento'
      preLoaderRoute: typeof TalentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidades': {
      id: '/universidades'
      path: '/universidades'
      fullPath: '/universidades'
      preLoaderRoute: typeof UniversidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistema/': {
      id: '/ecosistema/'
      path: '/'
      fullPath: '/ecosistema/'
      preLoaderRoute: typeof EcosistemaIndexRouteImport
      parentRoute: typeof EcosistemaRoute
    }
    '/ecosistema/$slug': {
      id: '/ecosistema/$slug'
      path: '/$slug'
      fullPath: '/ecosistema/$slug'
      preLoaderRoute: typeof EcosistemaSlugRouteImport
      parentRoute: typeof EcosistemaRoute
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
  }
}

interface EcosistemaRouteChildren {
  EcosistemaSlugRoute: typeof EcosistemaSlugRoute
  EcosistemaIndexRoute: typeof EcosistemaIndexRoute
}

const EcosistemaRouteChildren: EcosistemaRouteChildren = {
  EcosistemaSlugRoute: EcosistemaSlugRoute,
  EcosistemaIndexRoute: EcosistemaIndexRoute,
}

const EcosistemaRouteWithChildren = EcosistemaRoute._addFileChildren(
  EcosistemaRouteChildren,
)

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
  PodcastIndexRoute: typeof PodcastIndexRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
  PodcastIndexRoute: PodcastIndexRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliadosRoute: AliadosRoute,
  ContactoRoute: ContactoRoute,
  ConvocatoriasRoute: ConvocatoriasRoute,
  DatosRoute: DatosRoute,
  DirectorioRoute: DirectorioRoute,
  EcosistemaRoute: EcosistemaRouteWithChildren,
  EmpleoRoute: EmpleoRoute,
  EmpresasRoute: EmpresasRoute,
  EventosRoute: EventosRoute,
  HazParteRoute: HazParteRoute,
  HistoriasRoute: HistoriasRoute,
  InnovacionRoute: InnovacionRoute,
  InstitucionesRoute: InstitucionesRoute,
  InversionRoute: InversionRoute,
  MapaRoute: MapaRoute,
  NosotrosRoute: NosotrosRoute,
  NoticiasRoute: NoticiasRoute,
  OportunidadesRoute: OportunidadesRoute,
  PodcastRoute: PodcastRouteWithChildren,
  ProgramasRoute: ProgramasRoute,
  RetosRoute: RetosRoute,
  StartupsRoute: StartupsRoute,
  TalentoRoute: TalentoRoute,
  UniversidadesRoute: UniversidadesRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
